import Link from "next/link";
import booleanAlgebra from "@/app/data/iscXIIBooleanAlgebra";
import kMap from "@/app/data/iscXIIKMap";

function TruthTable({ title, rows, columns = ["A", "B", "Y"] }) {
  return <div className="overflow-hidden rounded-2xl border border-slate-200"><div className="border-b border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold">{title}</div><div className="overflow-x-auto"><table className="w-full text-center text-sm"><thead className="bg-slate-950 text-white"><tr>{columns.map((c)=><th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t border-slate-200">{columns.map((c)=><td key={c} className="px-4 py-3 font-mono">{r[c]}</td>)}</tr>)}</tbody></table></div></div>;
}

function Section({number,title,children}) { return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">{number}</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{title}</h2><div className="mt-5">{children}</div></section>; }

export default function BooleanAlgebraPage(){
 const starterExamples = Array.isArray(kMap.starterExamples) ? kMap.starterExamples : (kMap.examples || []);
 return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-6xl px-6 py-10">
  <Link href="/" className="text-sm text-slate-600">← Target95 Home</Link>
  <header className="mt-6 rounded-[2rem] bg-slate-950 p-8 text-white md:p-10"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-400">ISC Class XII · Flagship Chapter</p><h1 className="mt-3 text-4xl font-bold md:text-6xl">Boolean Algebra</h1><p className="mt-4 max-w-3xl text-lg text-slate-300">{booleanAlgebra.tagline}</p></header>
  <div className="mt-8 grid gap-6">
   <Section number="01" title="Learning path"><div className="grid gap-4 md:grid-cols-3">{booleanAlgebra.learningPath.map((x,i)=><article key={x.id} className="rounded-2xl border p-5"><div className="font-bold">{i+1}. {x.title}</div><p className="mt-2 text-sm text-slate-600">{x.goal}</p></article>)}</div></Section>
   <Section number="02" title="Boolean language & keywords"><div className="grid gap-4 md:grid-cols-3">{booleanAlgebra.terminology.map(x=><article key={x.term} className="rounded-2xl border p-5"><h3 className="font-bold">{x.term}</h3><p className="mt-2 text-sm text-slate-600">{x.meaning}</p><code className="mt-3 block rounded-xl bg-slate-950 p-3 text-sm text-white">{x.example}</code></article>)}</div></Section>
   <Section number="03" title="Logic gates & truth tables"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{booleanAlgebra.gateTable.map(x=><article key={x.gate} className="rounded-2xl border p-5"><div className="flex justify-between"><h3 className="font-bold">{x.gate}</h3><code>{x.notation}</code></div><p className="mt-2 text-sm font-semibold">{x.plain}</p><p className="mt-1 text-sm text-slate-600">{x.mental}</p><div className="mt-4">{x.gate==="NOT"?<TruthTable title="NOT" rows={booleanAlgebra.notTruthTable} columns={["A","Y"]}/>:<TruthTable title={x.gate} rows={booleanAlgebra.truthTables[x.gate]}/>}</div></article>)}</div></Section>
   <Section number="04" title="Gate conversion"><div className="grid gap-4 md:grid-cols-2">{booleanAlgebra.gateConversions.map(x=><article key={x.from+x.to} className="rounded-2xl border p-5"><div className="text-xs uppercase text-slate-500">{x.from} → {x.to}</div><div className="mt-2 rounded-xl bg-slate-950 p-4 font-mono text-sm text-white">{x.example}</div><ol className="mt-3 list-decimal pl-5 text-sm text-slate-600">{x.steps.map(s=><li key={s}>{s}</li>)}</ol></article>)}</div></Section>
   <Section number="05" title="Boolean laws"><div className="grid gap-4 md:grid-cols-2">{booleanAlgebra.lawDeck.map(x=><article key={x.name} className="rounded-2xl border p-5"><h3 className="font-bold">{x.name}</h3><div className="mt-3 flex flex-wrap gap-2">{x.rules.map(r=><code key={r} className="rounded bg-slate-950 px-3 py-2 text-white">{r}</code>)}</div><p className="mt-3 text-sm text-slate-600">{x.intuition}</p></article>)}</div></Section>
   <Section number="06" title="Minterms, Maxterms, SOP & POS"><div className="grid gap-4 md:grid-cols-2">{booleanAlgebra.terminology.filter(x=>["Minterm","Maxterm","Canonical SOP","Canonical POS","SOP","POS"].includes(x.term)).map(x=><article key={x.term} className="rounded-2xl border p-5"><h3 className="font-bold">{x.term}</h3><p className="mt-2 text-sm text-slate-600">{x.meaning}</p><code className="mt-3 block rounded bg-slate-950 p-3 text-white">{x.example}</code></article>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2">{booleanAlgebra.mintermMaxtermGuide.workedExamples.map(x=><article key={x.id} className="rounded-2xl bg-slate-50 p-5"><div className="text-sm font-semibold">{x.truthRow}</div><div className="mt-2 font-mono">{x.minterm||x.maxterm}</div><p className="mt-1 text-xs text-slate-500">{x.why}</p></article>)}</div></Section>
   <Section number="07" title="K-Map"><div className="grid gap-4 md:grid-cols-2"><article className="rounded-2xl bg-slate-50 p-6"><p className="text-sm text-slate-700">{kMap.purpose}</p><ul className="mt-4 list-disc space-y-2 pl-5 text-sm">{kMap.coreRules.map(r=><li key={r}>{r}</li>)}</ul></article><article className="rounded-2xl bg-slate-50 p-6"><ol className="list-decimal space-y-2 pl-5 text-sm">{kMap.workflow.map(r=><li key={r}>{r}</li>)}</ol></article></div><div className="mt-5 grid gap-4 md:grid-cols-3">{starterExamples.map(x=><article key={x.id} className="rounded-2xl border p-5"><div className="text-xs text-slate-500">{x.variables ?? x.expression}</div><div className="mt-2 font-mono">{x.minterms ?? x.expression}</div><div className="mt-2 font-bold">→ {x.result ?? x.answer}</div><p className="mt-1 text-sm text-slate-600">{x.idea ?? x.reason}</p></article>)}</div></Section>
   <Section number="08" title="Practice"><div className="grid gap-4 md:grid-cols-2">{(booleanAlgebra.mcqs||[]).map(x=><details key={x.id} className="rounded-2xl border p-4"><summary className="cursor-pointer font-semibold">{x.question}</summary><p className="mt-2 text-sm">Answer: {x.answer}</p><p className="mt-1 text-sm text-slate-600">{x.explanation}</p></details>)}</div></Section>
  </div>
 </div></main>;
}
