import json, os
qb = "src/app/data/question-bank"
os.makedirs(qb, exist_ok=True)

# Chapter 16: Exception Handling
ch16 = '''const chapter16 = {
  id: 16, title: "Exception Handling", slug: "exception-handling",
  description: "Learn try-catch-finally, throw, throws, checked vs unchecked exceptions.",
  topics: ["Try-Catch", "Finally", "Throw", "Throws", "Checked vs Unchecked"],
  mcqs: [
    { id: "CH16-MCQ-001", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "What is the purpose of try-catch?", options: ["A) Handle errors gracefully", "B) Ignore errors", "C) Crash the program", "D) Print errors"], correctAnswer: "A", explanation: "try-catch handles exceptions gracefully instead of crashing.", hint: "It catches errors.", estimatedTime: 15, marks: 1, tags: ["try-catch"] },
    { id: "CH16-MCQ-002", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Finally", question: "Which block always executes?", options: ["A) try", "B) catch", "C) finally", "D) throw"], correctAnswer: "C", explanation: "finally always executes, used for cleanup.", hint: "It finally runs.", estimatedTime: 10, marks: 1, tags: ["finally"] },
    { id: "CH16-MCQ-003", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Checked vs Unchecked", question: "Which is a checked exception?", options: ["A) RuntimeException", "B) IOException", "C) NullPointerException", "D) ArithmeticException"], correctAnswer: "B", explanation: "IOException is checked; must be declared or caught.", hint: "Which must be declared?", estimatedTime: 15, marks: 1, tags: ["checked", "IOException"] },
    { id: "CH16-MCQ-004", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Throw", question: "What does throw do?", options: ["A) Catches an exception", "B) Throws an exception explicitly", "C) Declares an exception", "D) Ignores an exception"], correctAnswer: "B", explanation: "throw explicitly throws an exception.", hint: "It throws manually.", estimatedTime: 15, marks: 1, tags: ["throw"] },
    { id: "CH16-MCQ-005", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Throws", question: "Difference between throw and throws?", options: ["A) throw throws, throws declares", "B) Same", "C) throw declares, throws throws", "D) Neither used"], correctAnswer: "A", explanation: "throw throws; throws declares in method signature.", hint: "One throws, one declares.", estimatedTime: 20, marks: 1, tags: ["throw", "throws"] },
    { id: "CH16-MCQ-006", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Checked vs Unchecked", question: "Which is unchecked?", options: ["A) IOException", "B) SQLException", "C) RuntimeException", "D) ClassNotFoundException"], correctAnswer: "C", explanation: "RuntimeException and subclasses are unchecked.", hint: "Which does not need catching?", estimatedTime: 15, marks: 1, tags: ["unchecked", "RuntimeException"] },
    { id: "CH16-MCQ-007", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Output? try{10/0}catch(ArithmeticException e){System.out.println(\\"Error\\");}", correctAnswer: "Error", explanation: "10/0 throws ArithmeticException, caught.", hint: "What does division by zero throw?", estimatedTime: 15, marks: 1, tags: ["ArithmeticException"] },
    { id: "CH16-MCQ-008", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Can you have multiple catch blocks?", options: ["A) Yes", "B) No", "C) Only two", "D) Only for checked"], correctAnswer: "A", explanation: "A try can have multiple catch blocks.", hint: "Can you catch different types?", estimatedTime: 10, marks: 1, tags: ["multiple catch"] }
  ],
  assertionReasons: [
    { id: "CH16-AR-001", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Assertion (A): The finally block always executes. Reason (R): It is used for cleanup code.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "finally always executes (except System.exit). Used for cleanup.", hint: "When does finally not execute?", estimatedTime: 20, marks: 2, tags: ["finally", "cleanup"] },
    { id: "CH16-AR-002", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Checked vs Unchecked", question: "Assertion (A): Checked exceptions must be handled at compile time. Reason (R): The compiler checks for proper exception handling.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "Checked exceptions must be declared or caught.", hint: "What happens if you do not handle a checked exception?", estimatedTime: 20, marks: 2, tags: ["checked", "compile time"] },
    { id: "CH16-AR-003", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Throw", question: "Assertion (A): You can throw any exception using throw. Reason (R): throw can throw both checked and unchecked exceptions.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "throw can throw any Throwable. Checked must be declared with throws.", hint: "Can you throw checked exceptions?", estimatedTime: 20, marks: 2, tags: ["throw", "checked"] },
    { id: "CH16-AR-004", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Assertion (A): A try block must be followed by catch or finally. Reason (R): The compiler requires exception handling code after try.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "A try block must be followed by at least one catch or finally.", hint: "Can try exist without catch or finally?", estimatedTime: 15, marks: 2, tags: ["try", "required"] }
  ],
  trueFalse: [
    { id: "CH16-TF-001", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "A try block can exist without a catch block.", correctAnswer: "True", explanation: "A try block can be followed by only a finally block.", hint: "Can try have only finally?", estimatedTime: 10, marks: 1, tags: ["try", "finally"] },
    { id: "CH16-TF-002", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Checked vs Unchecked", question: "RuntimeException is a checked exception.", correctAnswer: "False", explanation: "RuntimeException and subclasses are unchecked.", hint: "Is RuntimeException checked or unchecked?", estimatedTime: 10, marks: 1, tags: ["RuntimeException", "unchecked"] },
    { id: "CH16-TF-003", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Throw", question: "The throw statement can throw only unchecked exceptions.", correctAnswer: "False", explanation: "throw can throw both checked and unchecked exceptions.", hint: "Can you throw checked exceptions?", estimatedTime: 15, marks: 1, tags: ["throw", "checked"] },
    { id: "CH16-TF-004", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Multiple catch blocks must catch from most specific to most general.", correctAnswer: "True", explanation: "Specific exceptions must be caught before general ones.", hint: "What order should catch blocks be in?", estimatedTime: 15, marks: 1, tags: ["catch order", "specific"] },
    { id: "CH16-TF-005", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "If an exception is thrown in try, finally is skipped.", correctAnswer: "False", explanation: "finally always executes, even if an exception is thrown.", hint: "Does finally run after an exception?", estimatedTime: 15, marks: 1, tags: ["finally", "exception"] }
  ],
  fillBlanks: [
    { id: "CH16-FIB-001", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "The ________ block contains code that might throw an exception.", correctAnswer: "try", hint: "It tries to execute code.", estimatedTime: 10, marks: 1, tags: ["try"] },
    { id: "CH16-FIB-002", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "The ________ block catches and handles exceptions.", correctAnswer: "catch", hint: "It catches exceptions.", estimatedTime: 10, marks: 1, tags: ["catch"] },
    { id: "CH16-FIB-003", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Finally", question: "The ________ block always executes and is used for cleanup.", correctAnswer: "finally", hint: "It finally runs.", estimatedTime: 10, marks: 1, tags: ["finally"] },
    { id: "CH16-FIB-004", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Throw", question: "The ________ keyword explicitly throws an exception.", correctAnswer: "throw", hint: "It throws an exception.", estimatedTime: 10, marks: 1, tags: ["throw"] },
    { id: "CH16-FIB-005", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Throws", question: "The ________ keyword declares exceptions in a method signature.", correctAnswer: "throws", hint: "It throws a declaration.", estimatedTime: 10, marks: 1, tags: ["throws"] }
  ],
  outputQuestions: [
    { id: "CH16-OUT-001", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Output? try{10/2}catch(ArithmeticException e){System.out.println(\\"Error\\");}", correctAnswer: "5", explanation: "10/2 = 5, no exception.", hint: "Is there an exception?", estimatedTime: 10, marks: 1, tags: ["division"] },
    { id: "CH16-OUT-002", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Output? try{10/0}catch(ArithmeticException e){System.out.println(\\"Error\\");}finally{System.out.println(\\"Finally\\");}", correctAnswer: "Error\\nFinally", explanation: "Exception caught, finally always runs.", hint: "What runs after catch?", estimatedTime: 15, marks: 1, tags: ["finally"] },
    { id: "CH16-OUT-003", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Output? try{System.out.println(\\"A\\");}finally{System.out.println(\\"B\\");}", correctAnswer: "A\\nB", explanation: "No exception. try prints A, finally prints B.", hint: "Does finally run without exception?", estimatedTime: 10, marks: 1, tags: ["finally"] },
    { id: "CH16-OUT-004", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Throw", question: "Output? void check(int x){if(x<0)throw new IllegalArgumentException(\\"Negative\\");System.out.println(\\"OK\\");}", correctAnswer: "Negative", explanation: "check(-5) throws IllegalArgumentException.", hint: "What message is thrown?", estimatedTime: 20, marks: 2, tags: ["throw", "IllegalArgumentException"] },
    { id: "CH16-OUT-005", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Output? try{int[] a=new int[5];a[10];}catch(ArrayIndexOutOfBoundsException e){System.out.println(\\"Index error\\");}catch(Exception e){System.out.println(\\"General\\");}", correctAnswer: "Index error", explanation: "ArrayIndexOutOfBoundsException caught by first catch.", hint: "Which catch catches it?", estimatedTime: 20, marks: 2, tags: ["ArrayIndexOutOfBounds", "catch order"] }
  ],
  errorFinding: [
    { id: "CH16-ERR-001", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Find the error: try{10/0}", correctAnswer: "Missing catch or finally block.", hint: "What must follow a try block?", estimatedTime: 10, marks: 1, tags: ["missing catch"] },
    { id: "CH16-ERR-002", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Find the error: try{}catch(Exception e){}catch(ArithmeticException e){}", correctAnswer: "More specific exception must come before general.", hint: "What order should catch blocks be in?", estimatedTime: 15, marks: 2, tags: ["catch order"] },
    { id: "CH16-ERR-003", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Checked vs Unchecked", question: "Find the error: void readFile(){FileInputStream f=new FileInputStream(\\"file.txt\\");}", correctAnswer: "Must add throws IOException or try-catch.", hint: "What exception does FileInputStream throw?", estimatedTime: 15, marks: 2, tags: ["checked", "IOException"] }
  ],
  programmingQuestions: [
    { id: "CH16-PRQ-001", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", problemStatement: "Write a program that divides two numbers and handles ArithmeticException. Test with 10/0.", input: "10, 0", output: "Cannot divide by zero!", logic: "Use try-catch to handle division by zero.", solution: "public class Division { public static void main(String[] args) { try { System.out.println(10/0); } catch(ArithmeticException e) { System.out.println(\\"Cannot divide by zero!\\"); } } }", solutionExplanation: "try attempts division. catch handles ArithmeticException.", sampleTestCases: [{ input: "10, 0", output: "Cannot divide by zero!" }], estimatedTime: 240, marks: 4, tags: ["try-catch", "ArithmeticException"] },
    { id: "CH16-PRQ-002", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch-Finally", problemStatement: "Write a program that reads an array element and uses finally. Test with index 10 on a 5-element array.", input: "Array: {1,2,3,4,5}, index: 10", output: "Array index out of bounds!\\nOperation completed.", logic: "Use try-catch-finally.", solution: "public class ArrayAccess { public static void main(String[] args) { int[] arr={1,2,3,4,5}; try { System.out.println(arr[10]); } catch(ArrayIndexOutOfBoundsException e) { System.out.println(\\"Array index out of bounds!\\"); } finally { System.out.println(\\"Operation completed.\\\"); } } }", solutionExplanation: "try accesses invalid index. catch handles. finally always runs.", sampleTestCases: [{ input: "{1,2,3,4,5}, 10", output: "Array index out of bounds!\\nOperation completed." }], estimatedTime: 300, marks: 5, tags: ["try-catch-finally"] },
    { id: "CH16-PRQ-003", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Throw", problemStatement: "Write a program that validates age. If age < 0, throw IllegalArgumentException. Test with age = -5.", input: "age = -5", output: "Invalid age: -5", logic: "Use throw to explicitly throw an exception.", solution: "public class AgeValidator { static void validateAge(int age) { if(age<0) throw new IllegalArgumentException(\\"Invalid age: \\\"+age); System.out.println(\\"Valid age: \\\"+age); } public static void main(String[] args) { try { validateAge(-5); } catch(IllegalArgumentException e) { System.out.println(e.getMessage()); } } }", solutionExplanation: "validateAge throws for negative age. Main catches it.", sampleTestCases: [{ input: "-5", output: "Invalid age: -5" }], estimatedTime: 300, marks: 5, tags: ["throw", "IllegalArgumentException"] }
  ],
  debuggingQuestions: [
    { id: "CH16-DBG-001", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Identify and fix: try{10/0}", correctAnswer: "Add catch(ArithmeticException e){...}", hint: "What must follow a try block?", estimatedTime: 10, marks: 1, tags: ["missing catch"] },
    { id: "CH16-DBG-002", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Identify and fix: try{}catch(Exception e){}catch(NullPointerException e){}", correctAnswer: "More specific exception must come before general.", hint: "What order should catch blocks be in?", estimatedTime: 15, marks: 2, tags: ["catch order"] },
    { id: "CH16-DBG-003", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Checked vs Unchecked", question: "Identify and fix: void readFile(){FileInputStream f=new FileInputStream(\\"file.txt\\");}", correctAnswer: "Add throws IOException to method signature.", hint: "What exception does FileInputStream throw?", estimatedTime: 15, marks: 2, tags: ["checked exception"] }
  ],
  caseBasedQuestions: [
    { id: "CH16-CBQ-001", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "A banking application needs to handle: a) Division by zero b) Invalid input c) Array access d) Ensure DB connection closed", correctAnswer: "a) try-catch(ArithmeticException) b) try-catch(NumberFormatException) c) try-catch(ArrayIndexOutOfBoundsException) d) Use finally block", hint: "How do you ensure cleanup code always runs?", estimatedTime: 60, marks: 5, tags: ["exception handling", "banking"] },
    { id: "CH16-CBQ-002", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Throw", question: "A student grade system needs to: a) Validate marks b) Validate ID c) Handle file not found d) Create custom exception", correctAnswer: "a) throw IllegalArgumentException b) throw IllegalArgumentException c) try-catch(FileNotFoundException) d) class InvalidMarksException extends Exception", hint: "How do you create a custom exception?", estimatedTime: 75, marks: 5, tags: ["custom exception", "validation"] }
  ],
  vivaQuestions: [
    { id: "CH16-VIV-001", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "What is exception handling? Why is it important?", sampleAnswer: "Exception handling handles runtime errors so the normal flow continues. It prevents crashes and provides meaningful error messages.", estimatedTime: 20, marks: 2, tags: ["exception handling", "importance"] },
    { id: "CH16-VIV-002", difficulty: "easy", chapter: "Exception Handling", chapterId: 16, topic: "Checked vs Unchecked", question: "Difference between checked and unchecked exceptions?", sampleAnswer: "Checked must be declared or caught at compile time. Unchecked do not need declaration.", estimatedTime: 15, marks: 2, tags: ["checked", "unchecked"] },
    { id: "CH16-VIV-003", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "Order of try, catch, and finally blocks?", sampleAnswer: "try first, then catch (multiple allowed), then finally.", estimatedTime: 15, marks: 2, tags: ["order", "try-catch-finally"] },
    { id: "CH16-VIV-004", difficulty: "medium", chapter: "Exception Handling", chapterId: 16, topic: "Throw", question: "Difference between throw and throws?", sampleAnswer: "throw throws an exception within a method. throws declares exceptions in method signature.", estimatedTime: 20, marks: 2, tags: ["throw", "throws"] },
    { id: "CH16-VIV-005", difficulty: "hard", chapter: "Exception Handling", chapterId: 16, topic: "Try-Catch", question: "What is a custom exception? How do you create one?", sampleAnswer: "A user-defined exception class. Extend Exception (checked) or RuntimeException (unchecked).", estimatedTime: 25, marks: 3, tags: ["custom exception", "creation"] }
  ]
};

export default chapter16;
'''

# Chapter 17: Input/Output
ch17 = '''const chapter17 = {
  id: 17, title: "Input/Output", slug: "input-output",
  description: "Learn about Scanner, BufferedReader, System.in, System.out, and file I/O basics.",
  topics: ["Scanner", "BufferedReader", "System.in", "System.out", "File I/O"],
  mcqs: [
    { id: "CH17-MCQ-001", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Which class is used to read input from the user?", options: ["A) Scanner", "B) System", "C) InputStream", "D) BufferedReader"], correctAnswer: "A", explanation: "Scanner is used to read input from various sources including System.in.", hint: "It scans input.", estimatedTime: 10, marks: 1, tags: ["Scanner"] },
    { id: "CH17-MCQ-002", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "System.in", question: "What is System.in?", options: ["A) An output stream", "B) An input stream", "C) A class", "D) A method"], correctAnswer: "B", explanation: "System.in is a standard input stream that reads input from the keyboard.", hint: "Is it input or output?", estimatedTime: 10, marks: 1, tags: ["System.in", "input stream"] },
    { id: "CH17-MCQ-003", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Which method reads a line of text using Scanner?", options: ["A) next()", "B) nextLine()", "C) nextString()", "D) readLine()"], correctAnswer: "B", explanation: "nextLine() reads an entire line of text until Enter is pressed.", hint: "It reads a 'line'.", estimatedTime: 10, marks: 1, tags: ["nextLine"] },
    { id: "CH17-MCQ-004", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "BufferedReader", question: "Which class is faster for reading input?", options: ["A) Scanner", "B) BufferedReader", "C) System.in", "D) InputStream"], correctAnswer: "B", explanation: "BufferedReader is faster than Scanner because it reads larger chunks of data at once.", hint: "Which is more efficient?", estimatedTime: 15, marks: 1, tags: ["BufferedReader", "faster"] },
    { id: "CH17-MCQ-005", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "BufferedReader", question: "Which method reads a line using BufferedReader?", options: ["A) nextLine()", "B) readLine()", "C) readString()", "D) next()"], correctAnswer: "B", explanation: "readLine() is the method of BufferedReader that reads a line of text.", hint: "It 'reads' a 'line'.", estimatedTime: 10, marks: 1, tags: ["readLine", "BufferedReader"] },
    { id: "CH17-MCQ-006", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "System.out", question: "What is System.out?", options: ["A) An input stream", "B) An output stream", "C) A class", "D) A method"], correctAnswer: "B", explanation: "System.out is a standard output stream that prints output to the console.", hint: "Is it input or output?", estimatedTime: 10, marks: 1, tags: ["System.out", "output stream"] },
    { id: "CH17-MCQ-007", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Which method reads an integer using Scanner?", options: ["A) next()", "B) nextInt()", "C) nextLine()", "D) nextInteger()"], correctAnswer: "B", explanation: "nextInt() reads the next integer value from the Scanner.", hint: "It reads an 'Int'.", estimatedTime: 10, marks: 1, tags: ["nextInt"] },
    { id: "CH17-MCQ-008", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "System.out", question: "Which method prints a line with a newline?", options: ["A) print()", "B) println()", "C) printf()", "D) write()"], correctAnswer: "B", explanation: "println() prints the text and adds a newline at the end.", hint: "It 'prints a line'.", estimatedTime: 10, marks: 1, tags: ["println"] }
  ],
  assertionReasons: [
    { id: "CH17-AR-001", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Assertion (A): Scanner can read from any Readable source.\nReason (R): Scanner has constructors that accept InputStream, String, and File.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "Scanner is flexible and can read from multiple sources.", hint: "What can Scanner read from?", estimatedTime: 15, marks: 2, tags: ["Scanner", "sources"] },
    { id: "CH17-AR-002", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "BufferedReader", question: "Assertion (A): BufferedReader is faster than Scanner.\nReason (R): BufferedReader uses a larger buffer size.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "BufferedReader reads larger chunks, making it faster for large inputs.", hint: "Why is BufferedReader faster?", estimatedTime: 15, marks: 2, tags: ["BufferedReader", "faster"] },
    { id: "CH17-AR-003", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Assertion (A): After nextInt(), you should call nextLine() to consume the newline.\nReason (R): nextInt() does not consume the newline character.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "nextInt() leaves the newline in the buffer. nextLine() consumes it.", hint: "What happens after nextInt()?", estimatedTime: 20, marks: 2, tags: ["nextInt", "newline"] },
    { id: "CH17-AR-004", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "System.out", question: "Assertion (A): System.out.println() prints text and adds a newline.\nReason (R): The 'ln' in println stands for 'line'.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "println prints text and adds a newline. 'ln' stands for 'line'.", hint: "What does 'ln' mean?", estimatedTime: 10, marks: 2, tags: ["println", "newline"] }
  ],
  trueFalse: [
    { id: "CH17-TF-001", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Scanner is faster than BufferedReader.", correctAnswer: "False", explanation: "BufferedReader is faster because it uses a larger buffer.", hint: "Which is faster?", estimatedTime: 10, marks: 1, tags: ["BufferedReader", "faster"] },
    { id: "CH17-TF-002", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "System.in", question: "System.in is used for output.", correctAnswer: "False", explanation: "System.in is for input. System.out is for output.", hint: "Is System.in input or output?", estimatedTime: 10, marks: 1, tags: ["System.in", "input"] },
    { id: "CH17-TF-003", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "nextLine() reads a single word.", correctAnswer: "False", explanation: "nextLine() reads an entire line. next() reads a single word.", hint: "What does nextLine read?", estimatedTime: 10, marks: 1, tags: ["nextLine", "line"] },
    { id: "CH17-TF-004", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "BufferedReader", question: "BufferedReader requires exception handling.", correctAnswer: "True", explanation: "BufferedReader's readLine() throws IOException, which must be handled.", hint: "What exception does readLine throw?", estimatedTime: 15, marks: 1, tags: ["BufferedReader", "IOException"] },
    { id: "CH17-TF-005", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Scanner must be closed after use.", correctAnswer: "True", explanation: "Scanner should be closed to free resources. Use sc.close().", hint: "Should you close Scanner?", estimatedTime: 10, marks: 1, tags: ["Scanner", "close"] }
  ],
  fillBlanks: [
    { id: "CH17-FIB-001", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "The ________ class is used to read input from the user.", correctAnswer: "Scanner", hint: "It scans input.", estimatedTime: 10, marks: 1, tags: ["Scanner"] },
    { id: "CH17-FIB-002", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "System.in", question: "The ________ stream reads input from the keyboard.", correctAnswer: "System.in", hint: "It is the standard input.", estimatedTime: 10, marks: 1, tags: ["System.in"] },
    { id: "CH17-FIB-003", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "The ________ method of Scanner reads an integer value.", correctAnswer: "nextInt()", hint: "It reads an 'Int'.", estimatedTime: 10, marks: 1, tags: ["nextInt"] },
    { id: "CH17-FIB-004", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "BufferedReader", question: "The ________ method of BufferedReader reads a line of text.", correctAnswer: "readLine()", hint: "It reads a 'line'.", estimatedTime: 10, marks: 1, tags: ["readLine"] },
    { id: "CH17-FIB-005", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "System.out", question: "The ________ method prints text and adds a newline.", correctAnswer: "println()", hint: "It prints a 'line'.", estimatedTime: 10, marks: 1, tags: ["println"] }
  ],
  outputQuestions: [
    { id: "CH17-OUT-001", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "System.out", question: "What will be the output?\nSystem.out.print(\"Hello\");\nSystem.out.println(\"World\");", correctAnswer: "HelloWorld", explanation: "print does not add newline. println adds newline after World.", hint: "Does print add a newline?", estimatedTime: 10, marks: 1, tags: ["print", "println"] },
    { id: "CH17-OUT-002", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "System.out", question: "What will be the output?\nSystem.out.println(5 + 3);", correctAnswer: "8", explanation: "5 + 3 = 8. println prints the result.", hint: "What is 5 + 3?", estimatedTime: 10, marks: 1, tags: ["println", "addition"] },
    { id: "CH17-OUT-003", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "System.out", question: "What will be the output?\nSystem.out.println(\"5\" + 3);", correctAnswer: "53", explanation: "String concatenation: \"5\" + 3 = \"53\".", hint: "What happens when you add a String and an int?", estimatedTime: 15, marks: 1, tags: ["string concatenation"] },
    { id: "CH17-OUT-004", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "System.out", question: "What will be the output?\nSystem.out.printf(\"Name: %s, Age: %d\", \"Rahul\", 17);", correctAnswer: "Name: Rahul, Age: 17", explanation: "printf uses format specifiers: %s for string, %d for integer.", hint: "What do %s and %d mean?", estimatedTime: 20, marks: 2, tags: ["printf", "format"] },
    { id: "CH17-OUT-005", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "System.out", question: "What will be the output?\nSystem.out.println(1 + 2 + \"3\");", correctAnswer: "33", explanation: "1 + 2 = 3 (int), then 3 + \"3\" = \"33\" (string concatenation).", hint: "What is the order of operations?", estimatedTime: 20, marks: 2, tags: ["concatenation", "order"] }
  ],
  errorFinding: [
    { id: "CH17-ERR-001", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Find the error:\nScanner sc = new Scanner(System.in);\nint x = sc.nextLine();", correctAnswer: "nextLine() returns String, not int. Use nextInt() for integers.", hint: "What does nextLine return?", estimatedTime: 10, marks: 1, tags: ["type mismatch", "nextLine"] },
    { id: "CH17-ERR-002", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Find the error:\nScanner sc = new Scanner(System.in);\nint x = sc.nextInt();\nString s = sc.next();\n// Input: 10 Hello World", correctAnswer: "After nextInt(), newline remains. Call sc.nextLine() to consume it.", hint: "What happens after nextInt()?", estimatedTime: 15, marks: 2, tags: ["newline", "buffer"] },
    { id: "CH17-ERR-003", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "BufferedReader", question: "Find the error:\nBufferedReader br = new BufferedReader(new InputStreamReader(System.in));\nString s = br.readLine();", correctAnswer: "readLine() throws IOException. Must add throws or try-catch.", hint: "What exception does readLine throw?", estimatedTime: 15, marks: 2, tags: ["IOException", "BufferedReader"] }
  ],
  programmingQuestions: [
    { id: "CH17-PRQ-001", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "Scanner", problemStatement: "Write a program that reads a name and age using Scanner and displays them.", input: "Name: Priya, Age: 16", output: "Hello Priya! You are 16 years old.", logic: "Use Scanner to read String and int from System.in.", solution: "import java.util.Scanner; public class UserInfo { public static void main(String[] args) { Scanner sc = new Scanner(System.in); System.out.print(\\"Enter name: \\"); String name = sc.nextLine(); System.out.print(\\"Enter age: \\"); int age = sc.nextInt(); System.out.println(\\"Hello \" + name + \"! You are \" + age + \" years old.\"); sc.close(); } }", solutionExplanation: "Scanner reads name and age. Output displays them.", sampleTestCases: [{ input: "Priya, 16", output: "Hello Priya! You are 16 years old." }], estimatedTime: 300, marks: 5, tags: ["Scanner", "input"] },
    { id: "CH17-PRQ-002", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "BufferedReader", problemStatement: "Write a program using BufferedReader to read a line of text and print it in uppercase.", input: "hello world", output: "HELLO WORLD", logic: "Use BufferedReader to read a line, then toUpperCase().", solution: "import java.io.*; public class UpperCase { public static void main(String[] args) throws IOException { BufferedReader br = new BufferedReader(new InputStreamReader(System.in)); System.out.print(\\"Enter text: \\"); String s = br.readLine(); System.out.println(s.toUpperCase()); } }", solutionExplanation: "BufferedReader reads a line. toUpperCase converts to uppercase.", sampleTestCases: [{ input: "hello world", output: "HELLO WORLD" }], estimatedTime: 300, marks: 5, tags: ["BufferedReader", "toUpperCase"] },
    { id: "CH17-PRQ-003", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "Scanner", problemStatement: "Write a program that reads two numbers and prints their sum, difference, product, and quotient.", input: "10, 3", output: "Sum: 13\nDifference: 7\nProduct: 30\nQuotient: 3.33", logic: "Read two numbers, perform arithmetic operations.", solution: "import java.util.Scanner; public class Calculator { public static void main(String[] args) { Scanner sc = new Scanner(System.in); System.out.print(\\"Enter first number: \\"); int a = sc.nextInt(); System.out.print(\\"Enter second number: \\"); int b = sc.nextInt(); System.out.println(\\"Sum: \" + (a+b)); System.out.println(\\"Difference: \" + (a-b)); System.out.println(\\"Product: \" + (a*b)); System.out.printf(\\"Quotient: %.2f\\n\\", (double)a/b); sc.close(); } }", solutionExplanation: "Reads two numbers, performs all four operations.", sampleTestCases: [{ input: "10, 3", output: "Sum: 13\\nDifference: 7\\nProduct: 30\\nQuotient: 3.33" }], estimatedTime: 360, marks: 5, tags: ["Scanner", "calculator"] }
  ],
  debuggingQuestions: [
    { id: "CH17-DBG-001", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Identify and fix: Scanner sc = new Scanner(System.in); int x = sc.nextLine();", correctAnswer: "nextLine() returns String. Use nextInt() for integers.", hint: "What does nextLine return?", estimatedTime: 10, marks: 1, tags: ["type mismatch"] },
    { id: "CH17-DBG-002", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Identify and fix: Scanner sc = new Scanner(System.in); int x = sc.nextInt(); String s = sc.next();", correctAnswer: "After nextInt(), call sc.nextLine() to consume the newline.", hint: "What happens after nextInt()?", estimatedTime: 15, marks: 2, tags: ["newline", "buffer"] },
    { id: "CH17-DBG-003", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "BufferedReader", question: "Identify and fix: BufferedReader br = new BufferedReader(new InputStreamReader(System.in)); String s = br.readLine();", correctAnswer: "Add throws IOException or wrap in try-catch.", hint: "What exception does readLine throw?", estimatedTime: 15, marks: 2, tags: ["IOException"] }
  ],
  caseBasedQuestions: [
    { id: "CH17-CBQ-001", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "A student registration system needs to:\na) Read student name, age, and marks.\nb) Validate that age is positive.\nc) Calculate total and average.\nd) Display a formatted report.", correctAnswer: "Use Scanner for input. Validate age > 0. Calculate total/average. Use printf for formatted output.", hint: "How do you format output in Java?", estimatedTime: 60, marks: 5, tags: ["Scanner", "registration"] },
    { id: "CH17-CBQ-002", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "BufferedReader", question: "A text analysis tool needs to:\na) Read a paragraph from the user.\nb) Count the number of words.\nc) Count the number of characters.\nd) Find the longest word.", correctAnswer: "Use BufferedReader to read paragraph. Split by spaces for word count. Use length() for character count. Iterate to find longest word.", hint: "How do you split a string into words?", estimatedTime: 75, marks: 5, tags: ["BufferedReader", "text analysis"] }
  ],
  vivaQuestions: [
    { id: "CH17-VIV-001", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "How do you read input from the user in Java?", sampleAnswer: "Use Scanner: Scanner sc = new Scanner(System.in); int x = sc.nextInt(); String s = sc.nextLine();. Or use BufferedReader for faster reading.", estimatedTime: 15, marks: 2, tags: ["Scanner", "input"] },
    { id: "CH17-VIV-002", difficulty: "easy", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "What is the difference between next() and nextLine()?", sampleAnswer: "next() reads a single word (until whitespace). nextLine() reads an entire line (until Enter).", estimatedTime: 15, marks: 2, tags: ["next", "nextLine", "difference"] },
    { id: "CH17-VIV-003", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "BufferedReader", question: "What is the difference between Scanner and BufferedReader?", sampleAnswer: "Scanner is easier to use but slower. BufferedReader is faster but requires exception handling. Scanner has built-in parsing methods; BufferedReader requires manual parsing.", estimatedTime: 20, marks: 2, tags: ["Scanner", "BufferedReader", "difference"] },
    { id: "CH17-VIV-004", difficulty: "medium", chapter: "Input/Output", chapterId: 17, topic: "System.out", question: "What is the difference between print() and println()?", sampleAnswer: "print() prints text without a newline. println() prints text and adds a newline at the end.", estimatedTime: 15, marks: 2, tags: ["print", "println", "difference"] },
    { id: "CH17-VIV-005", difficulty: "hard", chapter: "Input/Output", chapterId: 17, topic: "Scanner", question: "Why should you close a Scanner after use?", sampleAnswer: "Closing a Scanner frees the underlying input stream and resources. Not closing can lead to resource leaks. Use sc.close() in a finally block or try-with-resources.", estimatedTime: 25, marks: 3, tags: ["Scanner", "close", "resources"] }
  ]
};

export default chapter17;
'''

# Chapter 18: Packages & Access Modifiers
ch18 = '''const chapter18 = {
  id: 18, title: "Packages & Access Modifiers", slug: "packages-access-modifiers",
  description: "Learn about packages, import statements, access modifiers, and the classpath.",
  topics: ["Packages", "Import", "Access Modifiers", "Classpath", "Package Structure"],
  mcqs: [
    { id: "CH18-MCQ-001", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "What is the purpose of a package in Java?", options: ["A) To organize classes and interfaces", "B) To create objects", "C) To handle errors", "D) To read input"], correctAnswer: "A", explanation: "Packages organize classes and interfaces into namespaces, preventing naming conflicts.", hint: "It organizes classes.", estimatedTime: 10, marks: 1, tags: ["package", "organization"] },
    { id: "CH18-MCQ-002", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Import", question: "Which keyword is used to import classes?", options: ["A) import", "B) package", "C) include", "D) require"], correctAnswer: "A", explanation: "The import keyword is used to bring classes from other packages into scope.", hint: "It 'imports' classes.", estimatedTime: 10, marks: 1, tags: ["import", "keyword"] },
    { id: "CH18-MCQ-003", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "Which access modifier is the most restrictive?", options: ["A) public", "B) protected", "C) private", "D) default"], correctAnswer: "C", explanation: "private is the most restrictive. Members are only accessible within the same class.", hint: "Which is the most restrictive?", estimatedTime: 10, marks: 1, tags: ["private", "restrictive"] },
    { id: "CH18-MCQ-004", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "Where must the package statement be in a Java file?", options: ["A) First line", "B) Last line", "C) After imports", "D) Anywhere"], correctAnswer: "A", explanation: "The package statement must be the first line (after comments) in a Java source file.", hint: "Where is the package statement?", estimatedTime: 10, marks: 1, tags: ["package", "first line"] },
    { id: "CH18-MCQ-005", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "Which access modifier allows access within the same package and subclasses?", options: ["A) private", "B) default", "C) protected", "D) public"], correctAnswer: "C", explanation: "protected allows access within the same package and by subclasses in any package.", hint: "Which is between default and public?", estimatedTime: 15, marks: 1, tags: ["protected", "subclass"] },
    { id: "CH18-MCQ-006", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "What is the default package?", options: ["A) java.lang", "B) java.util", "C) An unnamed package", "D) java.io"], correctAnswer: "C", explanation: "If no package is declared, the class is in the unnamed (default) package.", hint: "What happens if no package is declared?", estimatedTime: 15, marks: 1, tags: ["default package", "unnamed"] },
    { id: "CH18-MCQ-007", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Import", question: "Which import statement imports all classes from a package?", options: ["A) import java.util.*;", "B) import java.util; ", "C) import java.util.Class;", "D) import static java.util.*;"], correctAnswer: "A", explanation: "import java.util.*; imports all classes from the java.util package.", hint: "What does the * mean?", estimatedTime: 10, marks: 1, tags: ["wildcard import", "*"] },
    { id: "CH18-MCQ-008", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "Which access modifier provides the widest visibility?", options: ["A) private", "B) protected", "C) public", "D) default"], correctAnswer: "C", explanation: "public members are accessible from anywhere.", hint: "Which is the most visible?", estimatedTime: 10, marks: 1, tags: ["public", "widest"] }
  ],
  assertionReasons: [
    { id: "CH18-AR-001", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "Assertion (A): Packages prevent naming conflicts.\nReason (R): Classes in different packages can have the same name.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "Packages create namespaces. Classes in different packages can have the same name without conflict.", hint: "Can two classes have the same name in different packages?", estimatedTime: 15, marks: 2, tags: ["packages", "naming conflicts"] },
    { id: "CH18-AR-002", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "Assertion (A): private members are only accessible within the same class.\nReason (R): private is the most restrictive access modifier.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "private members are only visible within the declaring class. This is the most restrictive level.", hint: "Where can private members be accessed?", estimatedTime: 15, marks: 2, tags: ["private", "scope"] },
    { id: "CH18-AR-003", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "Assertion (A): A class can have only one public class per file.\nReason (R): The file name must match the public class name.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "A file can have at most one public class, and the file name must match it.", hint: "How many public classes per file?", estimatedTime: 15, marks: 2, tags: ["public class", "file name"] },
    { id: "CH18-AR-004", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Import", question: "Assertion (A): java.lang is automatically imported.\nReason (R): Common classes like String and System are in java.lang.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "java.lang is automatically imported in every Java program. No import statement needed.", hint: "Do you need to import String?", estimatedTime: 10, marks: 2, tags: ["java.lang", "automatic"] }
  ],
  trueFalse: [
    { id: "CH18-TF-001", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "A Java file can have multiple public classes.", correctAnswer: "False", explanation: "A Java file can have at most one public class.", hint: "How many public classes per file?", estimatedTime: 10, marks: 1, tags: ["public class", "file"] },
    { id: "CH18-TF-002", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Import", question: "java.lang package must be explicitly imported.", correctAnswer: "False", explanation: "java.lang is automatically imported in every Java program.", hint: "Do you need to import java.lang?", estimatedTime: 10, marks: 1, tags: ["java.lang", "automatic"] },
    { id: "CH18-TF-003", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "A protected member is accessible only within the same package.", correctAnswer: "False", explanation: "protected members are accessible within the same package AND by subclasses in other packages.", hint: "Can subclasses in other packages access protected members?", estimatedTime: 15, marks: 1, tags: ["protected", "subclass"] },
    { id: "CH18-TF-004", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "The package statement can appear anywhere in the file.", correctAnswer: "False", explanation: "The package statement must be the first non-comment line in the file.", hint: "Where must the package statement be?", estimatedTime: 10, marks: 1, tags: ["package", "position"] },
    { id: "CH18-TF-005", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "A class member without any access modifier has public access.", correctAnswer: "False", explanation: "A member without an access modifier has default (package-private) access.", hint: "What is the default access level?", estimatedTime: 15, marks: 1, tags: ["default", "no modifier"] }
  ],
  fillBlanks: [
    { id: "CH18-FIB-001", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "A group of related classes and interfaces is called a ________.", correctAnswer: "package", hint: "It packages classes together.", estimatedTime: 10, marks: 1, tags: ["package"] },
    { id: "CH18-FIB-002", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Import", question: "The ________ keyword is used to import classes from other packages.", correctAnswer: "import", hint: "It imports classes.", estimatedTime: 10, marks: 1, tags: ["import"] },
    { id: "CH18-FIB-003", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "The ________ access modifier allows access only within the same class.", correctAnswer: "private", hint: "It is the most restrictive.", estimatedTime: 10, marks: 1, tags: ["private"] },
    { id: "CH18-FIB-004", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "The ________ access modifier allows access from anywhere.", correctAnswer: "public", hint: "It is the most visible.", estimatedTime: 10, marks: 1, tags: ["public"] },
    { id: "CH18-FIB-005", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "The ________ access modifier allows access within the same package and by subclasses.", correctAnswer: "protected", hint: "It protects access while allowing subclass access.", estimatedTime: 15, marks: 1, tags: ["protected"] }
  ],
  outputQuestions: [
    { id: "CH18-OUT-001", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "What is the output?\npackage com.example;\npublic class Test {\n    public static void main(String[] args) {\n        System.out.println(\"Hello\");\n    }\n}", correctAnswer: "Hello", explanation: "The package declaration does not affect the output. The program prints 'Hello'.", hint: "Does the package affect output?", estimatedTime: 10, marks: 1, tags: ["package", "output"] },
    { id: "CH18-OUT-002", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "What will be the output?\nclass A {\n    private int x = 10;\n    public int getX() { return x; }\n}\nclass B {\n    public static void main(String[] args) {\n        A a = new A();\n        System.out.println(a.getX());\n    }\n}", correctAnswer: "10", explanation: "x is private but accessible through the public getter method getX().", hint: "Can you access private fields through public methods?", estimatedTime: 15, marks: 1, tags: ["private", "getter"] },
    { id: "CH18-OUT-003", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Import", question: "What will be the output?\nimport java.util.ArrayList;\npublic class Test {\n    public static void main(String[] args) {\n        ArrayList<String> list = new ArrayList<>();\n        list.add(\"Hello\");\n        System.out.println(list.get(0));\n    }\n}", correctAnswer: "Hello", explanation: "ArrayList is imported and used to store and retrieve strings.", hint: "What does list.get(0) return?", estimatedTime: 15, marks: 1, tags: ["ArrayList", "import"] },
    { id: "CH18-OUT-004", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "What will be the output?\nclass A {\n    int x = 5;\n}\nclass B extends A {\n    void display() { System.out.println(x); }\n}\npublic class Test {\n    public static void main(String[] args) {\n        new B().display();\n    }\n}", correctAnswer: "5", explanation: "x has default access. B is in the same package, so it can access x.", hint: "Can classes in the same package access default members?", estimatedTime: 15, marks: 1, tags: ["default", "same package"] },
    { id: "CH18-OUT-005", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "What will be the output?\nimport static java.lang.Math.*;\npublic class Test {\n    public static void main(String[] args) {\n        System.out.println(max(10, 20));\n    }\n}", correctAnswer: "20", explanation: "import static imports all static members of Math. max(10, 20) returns 20.", hint: "What does import static do?", estimatedTime: 15, marks: 1, tags: ["import static", "Math"] }
  ],
  errorFinding: [
    { id: "CH18-ERR-001", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "Find the error:\npackage com.example;\npublic class Test { }\n// File name: Test.java", correctAnswer: "No error. File name matches the public class name.", hint: "Does the file name match the class name?", estimatedTime: 10, marks: 1, tags: ["file name", "correct"] },
    { id: "CH18-ERR-002", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "Find the error:\npackage com.example;\npublic class Test { }\n// File name: Example.java", correctAnswer: "File name must match the public class name. Rename to Test.java.", hint: "What should the file name be?", estimatedTime: 10, marks: 1, tags: ["file name", "mismatch"] },
    { id: "CH18-ERR-003", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "Find the error:\nclass A {\n    private int x = 10;\n}\nclass B {\n    void display() { System.out.println(x); }\n}", correctAnswer: "x is private in A and not accessible in B. Add a public getter method.", hint: "Can you access private members from another class?", estimatedTime: 15, marks: 2, tags: ["private", "access"] }
  ],
  programmingQuestions: [
    { id: "CH18-PRQ-001", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", problemStatement: "Create a package 'com.school' with a class 'Student' that has private fields and public getters/setters.", input: "No input.", output: "Name: Priya, Age: 16", logic: "Create a class with encapsulation in a package.", solution: "package com.school; public class Student { private String name; private int age; public String getName() { return name; } public void setName(String n) { name = n; } public int getAge() { return age; } public void setAge(int a) { age = a; } }", solutionExplanation: "Package declaration, private fields, public getters/setters.", sampleTestCases: [{ input: "No input", output: "Name: Priya, Age: 16" }], estimatedTime: 300, marks: 5, tags: ["package", "encapsulation"] },
    { id: "CH18-PRQ-002", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Import", problemStatement: "Write a program that imports ArrayList from java.util and demonstrates its use.", input: "No input.", output: "List: [Apple, Banana, Cherry]", logic: "Import ArrayList, add elements, print the list.", solution: "import java.util.ArrayList; public class ListDemo { public static void main(String[] args) { ArrayList<String> list = new ArrayList<>(); list.add(\"Apple\"); list.add(\"Banana\"); list.add(\"Cherry\"); System.out.println(\"List: \" + list); } }", solutionExplanation: "Import ArrayList, add elements, print using toString().", sampleTestCases: [{ input: "No input", output: "List: [Apple, Banana, Cherry]" }], estimatedTime: 300, marks: 5, tags: ["import", "ArrayList"] },
    { id: "CH18-PRQ-003", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", problemStatement: "Create a class with all four access modifiers and demonstrate their visibility.", input: "No input.", output: "publicVar: 1\nprotectedVar: 2\ndefaultVar: 3", logic: "Create fields with public, protected, default, and private access. Show which are accessible.", solution: "class Test { public int publicVar = 1; protected int protectedVar = 2; int defaultVar = 3; private int privateVar = 4; } public class AccessDemo { public static void main(String[] args) { Test t = new Test(); System.out.println(\"publicVar: \" + t.publicVar); System.out.println(\"protectedVar: \" + t.protectedVar); System.out.println(\"defaultVar: \" + t.defaultVar); } }", solutionExplanation: "Demonstrates public, protected, and default access. privateVar is not accessible.", sampleTestCases: [{ input: "No input", output: "publicVar: 1\\nprotectedVar: 2\\ndefaultVar: 3" }], estimatedTime: 360, marks: 5, tags: ["access modifiers", "visibility"] }
  ],
  debuggingQuestions: [
    { id: "CH18-DBG-001", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "Identify and fix: File name is Example.java but class is public class Test.", correctAnswer: "Rename file to Test.java to match the public class name.", hint: "What should the file name match?", estimatedTime: 10, marks: 1, tags: ["file name", "mismatch"] },
    { id: "CH18-DBG-002", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "Identify and fix: class A { private int x; } class B { void show() { System.out.println(x); } }", correctAnswer: "x is private in A. Add a public getter method in A.", hint: "Can you access private members from another class?", estimatedTime: 15, marks: 2, tags: ["private", "access"] },
    { id: "CH18-DBG-003", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "Identify and fix: package statement is not the first line.", correctAnswer: "Move the package statement to the first non-comment line.", hint: "Where must the package statement be?", estimatedTime: 15, marks: 2, tags: ["package", "position"] }
  ],
  caseBasedQuestions: [
    { id: "CH18-CBQ-001", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "A software company needs to organize their code:\na) Create a package structure for a banking system.\nb) What classes would go in each package?\nc) How would you import classes from other packages?\nd) What access modifiers would you use for sensitive data?", correctAnswer: "a) com.bank.account, com.bank.customer, com.bank.transaction\nb) Account, Customer, Transaction classes in respective packages.\nc) import com.bank.account.Account;\nd) Use private for sensitive data, public for getters/setters.", hint: "How do you organize a large project?", estimatedTime: 60, marks: 5, tags: ["packages", "organization"] },
    { id: "CH18-CBQ-002", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "A library management system needs to:\na) Create a Book class with private fields.\nb) Provide public getters/setters.\nc) Allow only same-package classes to access certain fields.\nd) Create a subclass in a different package that accesses protected fields.", correctAnswer: "a) private String title, author; b) public String getTitle() { return title; } etc. c) Use default access for package-specific fields. d) protected fields accessible in subclass.", hint: "How do you control access at different levels?", estimatedTime: 75, marks: 5, tags: ["access modifiers", "library"] }
  ],
  vivaQuestions: [
    { id: "CH18-VIV-001", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "What is a package? Why is it used?", sampleAnswer: "A package is a namespace that organizes classes and interfaces. It prevents naming conflicts, controls access, and makes code easier to manage.", estimatedTime: 15, marks: 2, tags: ["package", "purpose"] },
    { id: "CH18-VIV-002", difficulty: "easy", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "What are the four access modifiers in Java?", sampleAnswer: "1) private - same class only. 2) default (no modifier) - same package. 3) protected - same package + subclasses. 4) public - anywhere.", estimatedTime: 15, marks: 2, tags: ["access modifiers", "list"] },
    { id: "CH18-VIV-003", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Import", question: "What is the difference between import and import static?", sampleAnswer: "import imports classes from other packages. import static imports static members (fields and methods) from a class, allowing you to use them without the class name.", estimatedTime: 20, marks: 2, tags: ["import", "import static", "difference"] },
    { id: "CH18-VIV-004", difficulty: "medium", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Packages", question: "Why must the file name match the public class name?", sampleAnswer: "The Java compiler and JVM use the file name to find the class. A public class must be in a file with the same name so the compiler can locate it.", estimatedTime: 15, marks: 2, tags: ["file name", "public class"] },
    { id: "CH18-VIV-005", difficulty: "hard", chapter: "Packages & Access Modifiers", chapterId: 18, topic: "Access Modifiers", question: "When would you use protected vs default access?", sampleAnswer: "Use protected when you want subclasses (even in different packages) to access a member. Use default when only classes in the same package should access it. Protected is wider than default.", estimatedTime: 25, marks: 3, tags: ["protected", "default", "comparison"] }
  ]
};

export default chapter18;
'''

# Chapter 19: OOP Concepts Overview
ch19 = '''const chapter19 = {
  id: 19, title: "OOP Concepts Overview", slug: "oop-concepts",
  description: "Comprehensive review of OOP principles: Encapsulation, Inheritance, Polymorphism, Abstraction, and their applications.",
  topics: ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction", "OOP Principles"],
  mcqs: [
    { id: "CH19-MCQ-001", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Which of the following is NOT one of the four pillars of OOP?", options: ["A) Encapsulation", "B) Inheritance", "C) Polymorphism", "D) Compilation"], correctAnswer: "D", explanation: "The four pillars are Encapsulation, Inheritance, Polymorphism, and Abstraction. Compilation is not an OOP concept.", hint: "What are the four pillars of OOP?", estimatedTime: 15, marks: 1, tags: ["OOP pillars"] },
    { id: "CH19-MCQ-002", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Which OOP concept hides internal implementation details?", options: ["A) Inheritance", "B) Polymorphism", "C) Abstraction", "D) Encapsulation"], correctAnswer: "C", explanation: "Abstraction hides complex implementation details and shows only the essential features.", hint: "Which concept hides details?", estimatedTime: 15, marks: 1, tags: ["abstraction", "hiding"] },
    { id: "CH19-MCQ-003", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Which OOP concept is demonstrated by a class having private fields and public methods?", options: ["A) Inheritance", "B) Polymorphism", "C) Abstraction", "D) Encapsulation"], correctAnswer: "D", explanation: "Encapsulation bundles data and methods, hiding internal state by making fields private.", hint: "Which concept bundles data and methods?", estimatedTime: 15, marks: 1, tags: ["encapsulation"] },
    { id: "CH19-MCQ-004", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Which OOP concept allows a class to have multiple methods with the same name?", options: ["A) Inheritance", "B) Polymorphism", "C) Abstraction", "D) Encapsulation"], correctAnswer: "B", explanation: "Polymorphism includes method overloading (same name, different parameters) and overriding.", hint: "Which concept includes overloading?", estimatedTime: 15, marks: 1, tags: ["polymorphism", "overloading"] },
    { id: "CH19-MCQ-005", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Which OOP concept is demonstrated when a subclass provides its own implementation of a parent method?", options: ["A) Inheritance", "B) Polymorphism", "C) Abstraction", "D) Encapsulation"], correctAnswer: "B", explanation: "Method overriding is a form of runtime polymorphism.", hint: "Which concept includes overriding?", estimatedTime: 15, marks: 1, tags: ["polymorphism", "overriding"] },
    { id: "CH19-MCQ-006", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Which OOP concept creates an IS-A relationship?", options: ["A) Inheritance", "B) Polymorphism", "C) Abstraction", "D) Encapsulation"], correctAnswer: "A", explanation: "Inheritance creates an IS-A relationship between parent and child classes.", hint: "Which concept creates IS-A?", estimatedTime: 15, marks: 1, tags: ["inheritance", "IS-A"] },
    { id: "CH19-MCQ-007", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Which OOP concept creates a HAS-A relationship?", options: ["A) Inheritance", "B) Polymorphism", "C) Abstraction", "D) Encapsulation"], correctAnswer: "D", explanation: "Encapsulation (using objects as fields) creates a HAS-A relationship.", hint: "Which concept creates HAS-A?", estimatedTime: 15, marks: 1, tags: ["encapsulation", "HAS-A"] },
    { id: "CH19-MCQ-008", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "What is the main benefit of OOP?", options: ["A) Faster execution", "B) Code reusability", "C) Smaller programs", "D) Fewer bugs"], correctAnswer: "B", explanation: "OOP promotes code reusability through inheritance and polymorphism, making development faster and more maintainable.", hint: "What is the main benefit of OOP?", estimatedTime: 15, marks: 1, tags: ["benefits", "reusability"] }
  ],
  assertionReasons: [
    { id: "CH19-AR-001", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Assertion (A): Encapsulation and Abstraction are complementary.\nReason (R): Encapsulation hides data; abstraction hides implementation.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "Both hide information at different levels. Encapsulation hides data; abstraction hides implementation.", hint: "How are encapsulation and abstraction related?", estimatedTime: 20, marks: 2, tags: ["encapsulation", "abstraction"] },
    { id: "CH19-AR-002", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Assertion (A): Inheritance promotes code reusability.\nReason (R): A subclass inherits fields and methods from its superclass.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "Inheritance allows subclasses to reuse superclass code, reducing duplication.", hint: "How does inheritance promote reusability?", estimatedTime: 15, marks: 2, tags: ["inheritance", "reusability"] },
    { id: "CH19-AR-003", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Assertion (A): Polymorphism increases code flexibility.\nReason (R): A single interface can represent different underlying forms.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "Polymorphism allows one interface to work with different types, increasing flexibility.", hint: "How does polymorphism increase flexibility?", estimatedTime: 20, marks: 2, tags: ["polymorphism", "flexibility"] },
    { id: "CH19-AR-004", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Assertion (A): Abstraction simplifies complex systems.\nReason (R): It hides unnecessary details from the user.", options: ["A) Both A and R are true, and R is the correct explanation of A", "B) Both A and R are true, but R is NOT the correct explanation of A", "C) A is true, but R is false", "D) A is false, but R is true"], correctAnswer: "A", explanation: "Abstraction simplifies by showing only essential features and hiding complexity.", hint: "How does abstraction simplify?", estimatedTime: 15, marks: 2, tags: ["abstraction", "simplification"] }
  ],
  trueFalse: [
    { id: "CH19-TF-001", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Encapsulation and Abstraction are the same concept.", correctAnswer: "False", explanation: "They are related but different. Encapsulation hides data; abstraction hides implementation.", hint: "Are they the same?", estimatedTime: 10, marks: 1, tags: ["encapsulation", "abstraction", "different"] },
    { id: "CH19-TF-002", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Inheritance creates an IS-A relationship.", correctAnswer: "True", explanation: "A subclass IS-A superclass. Example: Dog IS-A Animal.", hint: "What relationship does inheritance create?", estimatedTime: 10, marks: 1, tags: ["inheritance", "IS-A"] },
    { id: "CH19-TF-003", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Polymorphism means 'one form'.", correctAnswer: "False", explanation: "Polymorphism means 'many forms'. It allows one interface to represent multiple forms.", hint: "What does polymorphism mean?", estimatedTime: 10, marks: 1, tags: ["polymorphism", "meaning"] },
    { id: "CH19-TF-004", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Abstraction can be achieved using abstract classes and interfaces.", correctAnswer: "True", explanation: "Abstract classes and interfaces both provide abstraction by hiding implementation details.", hint: "How is abstraction achieved?", estimatedTime: 15, marks: 1, tags: ["abstraction", "abstract class", "interface"] },
    { id: "CH19-TF-005", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "All four OOP pillars are independent of each other.", correctAnswer: "False", explanation: "The pillars are interrelated. Inheritance enables polymorphism. Encapsulation supports abstraction.", hint: "Are the OOP pillars independent?", estimatedTime: 15, marks: 1, tags: ["interrelated", "pillars"] }
  ],
  fillBlanks: [
    { id: "CH19-FIB-001", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "The four pillars of OOP are Encapsulation, Inheritance, Polymorphism, and ________.", correctAnswer: "Abstraction", hint: "It starts with 'A'.", estimatedTime: 10, marks: 1, tags: ["abstraction", "pillars"] },
    { id: "CH19-FIB-002", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Polymorphism means ________ forms.", correctAnswer: "many", hint: "It is the opposite of 'mono'.", estimatedTime: 10, marks: 1, tags: ["polymorphism", "meaning"] },
    { id: "CH19-FIB-003", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "The IS-A relationship is created by ________.", correctAnswer: "inheritance", hint: "It is one of the four pillars.", estimatedTime: 10, marks: 1, tags: ["inheritance", "IS-A"] },
    { id: "CH19-FIB-004", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "The HAS-A relationship is created by ________.", correctAnswer: "encapsulation", hint: "It involves using objects as fields.", estimatedTime: 10, marks: 1, tags: ["encapsulation", "HAS-A"] },
    { id: "CH19-FIB-005", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Hiding internal implementation details is called ________.", correctAnswer: "abstraction", hint: "It starts with 'A'.", estimatedTime: 10, marks: 1, tags: ["abstraction", "hiding"] }
  ],
  outputQuestions: [
    { id: "CH19-OUT-001", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Output?\nclass A { void show() { System.out.println(\"A\"); } }\nclass B extends A { void show() { System.out.println(\"B\"); } }\npublic class Test { public static void main(String[] args) { A a = new B(); a.show(); } }", correctAnswer: "B", explanation: "Runtime polymorphism: A reference, B object. B's show() is called.", hint: "Which show() is called at runtime?", estimatedTime: 15, marks: 1, tags: ["polymorphism", "overriding"] },
    { id: "CH19-OUT-002", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Output?\nclass A { int x = 10; }\nclass B extends A { int x = 20; void show() { System.out.println(x + \" \" + super.x); } }\npublic class Test { public static void main(String[] args) { new B().show(); } }", correctAnswer: "20 10", explanation: "x refers to B's x (20). super.x refers to A's x (10).", hint: "What does super.x refer to?", estimatedTime: 20, marks: 2, tags: ["super", "variable hiding"] },
    { id: "CH19-OUT-003", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Output?\nabstract class A { abstract void show(); void display() { System.out.println(\"A\"); } }\nclass B extends A { void show() { System.out.println(\"B\"); } }\npublic class Test { public static void main(String[] args) { A a = new B(); a.show(); a.display(); } }", correctAnswer: "B\nA", explanation: "show() is abstract in A, overridden in B. display() is concrete in A.", hint: "Which methods are abstract vs concrete?", estimatedTime: 20, marks: 2, tags: ["abstract", "inheritance"] },
    { id: "CH19-OUT-004", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Output?\nclass A { void show() { System.out.println(\"A\"); } }\nclass B extends A { void show() { System.out.println(\"B\"); } }\nclass C extends B { public static void main(String[] args) { A a = new C(); a.show(); } }\n", correctAnswer: "B", explanation: "C extends B, B overrides show(). A reference to C calls B's show().", hint: "Which class overrides show()?", estimatedTime: 20, marks: 2, tags: ["multi-level", "overriding"] },
    { id: "CH19-OUT-005", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Output?\nclass A { A() { System.out.print(\"A \"); } }\nclass B extends A { B() { System.out.print(\"B \"); } }\nclass C extends B { C() { System.out.print(\"C \"); } }\npublic class Test { public static void main(String[] args) { new C(); } }", correctAnswer: "A B C", explanation: "Constructor chaining: A constructor calls B constructor calls C constructor.", hint: "What is the order of constructor execution?", estimatedTime: 20, marks: 2, tags: ["constructor chaining", "multi-level"] }
  ],
  errorFinding: [
    { id: "CH19-ERR-001", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Find the error:\nabstract class A { abstract void show(); }\nclass B extends A { }", correctAnswer: "B does not implement abstract method show().", hint: "What must a concrete subclass do?", estimatedTime: 10, marks: 1, tags: ["abstract", "implementation"] },
    { id: "CH19-ERR-002", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Find the error:\nabstract class A { } class B extends A { }\npublic class Test { public static void main(String[] args) { A a = new A(); } }", correctAnswer: "Cannot instantiate abstract class A.", hint: "Can you create an object of an abstract class?", estimatedTime: 10, marks: 1, tags: ["abstract", "instantiate"] },
    { id: "CH19-ERR-003", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Find the error:\nclass A { void show() { } }\nclass B extends A { private void show() { } }", correctAnswer: "Cannot reduce visibility of overridden method.", hint: "Can an overriding method be more restrictive?", estimatedTime: 15, marks: 2, tags: ["overriding", "visibility"] }
  ],
  programmingQuestions: [
    { id: "CH19-PRQ-001", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", problemStatement: "Create a class hierarchy demonstrating all four OOP pillars: Animal (abstract) -> Dog, Cat.", input: "No input.", output: "Dog barks\nCat meows", logic: "Use abstract class for Animal, override methods in subclasses.", solution: "abstract class Animal { abstract void makeSound(); } class Dog extends Animal { void makeSound() { System.out.println(\"Dog barks\"); } } class Cat extends Animal { void makeSound() { System.out.println(\"Cat meows\"); } } public class Test { public static void main(String[] args) { Animal a1 = new Dog(); Animal a2 = new Cat(); a1.makeSound(); a2.makeSound(); } }", solutionExplanation: "Abstraction (abstract class), Inheritance (extends), Polymorphism (Animal reference).", sampleTestCases: [{ input: "No input", output: "Dog barks\nCat meows" }], estimatedTime: 300, marks: 5, tags: ["OOP", "abstraction", "inheritance"] },
    { id: "CH19-PRQ-002", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", problemStatement: "Create a Shape hierarchy with encapsulation and polymorphism. Shape (abstract) -> Circle, Rectangle.", input: "No input.", output: "Circle area: 78.5\nRectangle area: 24.0", logic: "Abstract class with abstract area(). Subclasses implement area().", solution: "abstract class Shape { abstract double area(); } class Circle extends Shape { double r; Circle(double r) { this.r = r; } double area() { return 3.14 * r * r; } } class Rectangle extends Shape { double l, b; Rectangle(double l, double b) { this.l = l; this.b = b; } double area() { return l * b; } } public class Test { public static void main(String[] args) { Shape[] shapes = { new Circle(5), new Rectangle(6, 4) }; for (Shape s : shapes) System.out.println(s.getClass().getSimpleName() + \" area: \" + s.area()); } }", solutionExplanation: "Uses abstraction, inheritance, polymorphism (array of Shape), encapsulation (private fields).", sampleTestCases: [{ input: "No input", output: "Circle area: 78.5\nRectangle area: 24.0" }], estimatedTime: 360, marks: 5, tags: ["OOP", "polymorphism", "Shape"] },
    { id: "CH19-PRQ-003", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", problemStatement: "Create a BankAccount class demonstrating encapsulation with validation, and a SavingsAccount subclass demonstrating inheritance and polymorphism.", input: "No input.", output: "Balance: 1000.0\nInterest: 50.0", logic: "BankAccount has private balance with getter/setter. SavingsAccount extends and adds interest calculation.", solution: "class BankAccount { private double balance; public BankAccount(double b) { balance = b; } public double getBalance() { return balance; } public void deposit(double amt) { if(amt > 0) balance += amt; } } class SavingsAccount extends BankAccount { public SavingsAccount(double b) { super(b); } public double calculateInterest() { return getBalance() * 0.05; } } public class Test { public static void main(String[] args) { SavingsAccount acc = new SavingsAccount(1000); System.out.println(\"Balance: \" + acc.getBalance()); System.out.println(\"Interest: \" + acc.calculateInterest()); } }", solutionExplanation: "Encapsulation (private balance), Inheritance (extends), Polymorphism (SavingsAccount as BankAccount).", sampleTestCases: [{ input: "No input", output: "Balance: 1000.0\nInterest: 50.0" }], estimatedTime: 360, marks: 5, tags: ["OOP", "encapsulation", "BankAccount"] }
  ],
  debuggingQuestions: [
    { id: "CH19-DBG-001", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Identify and fix: abstract class A { abstract void show(); } class B extends A { }", correctAnswer: "B must implement show() or be declared abstract.", hint: "What must a concrete subclass do?", estimatedTime: 10, marks: 1, tags: ["abstract", "implementation"] },
    { id: "CH19-DBG-002", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Identify and fix: class A { void show() { } } class B extends A { private void show() { } }", correctAnswer: "Overriding method cannot be more restrictive. Remove private or make parent method private.", hint: "Can an overriding method be more restrictive?", estimatedTime: 15, marks: 2, tags: ["overriding", "visibility"] },
    { id: "CH19-DBG-003", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "Identify and fix: abstract class A { } class B extends A { } public class Test { public static void main(String[] args) { A a = new A(); } }", correctAnswer: "Cannot instantiate abstract class A. Use A a = new B(); instead.", hint: "Can you create an object of an abstract class?", estimatedTime: 15, marks: 2, tags: ["abstract", "instantiate"] }
  ],
  caseBasedQuestions: [
    { id: "CH19-CBQ-001", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "A vehicle rental system needs to:\na) Use abstraction for Vehicle base class.\nb) Use inheritance for Car, Bike, Truck subclasses.\nc) Use polymorphism to process different vehicles.\nd) Use encapsulation for vehicle data.", correctAnswer: "a) abstract class Vehicle with abstract rent() method.\nb) Car, Bike, Truck extend Vehicle.\nc) Vehicle[] vehicles = {new Car(), new Bike(), new Truck()}.\nd) private fields with getters/setters.", hint: "How do you apply all four pillars together?", estimatedTime: 60, marks: 5, tags: ["OOP", "vehicle", "all pillars"] },
    { id: "CH19-CBQ-002", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "A banking system needs to:\na) Use encapsulation for Account (private balance).\nb) Use inheritance for SavingsAccount, CurrentAccount.\nc) Use polymorphism for processing transactions.\nd) Use abstraction for Account base class.", correctAnswer: "a) private double balance with getters/setters.\nb) SavingsAccount, CurrentAccount extend Account.\nc) Account[] accounts = {new SavingsAccount(), new CurrentAccount()}.\nd) abstract class Account with abstract methods.", hint: "How do you design a flexible banking system using OOP?", estimatedTime: 75, marks: 5, tags: ["OOP", "banking", "all pillars"] }
  ],
  vivaQuestions: [
    { id: "CH19-VIV-001", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "What are the four pillars of OOP?", sampleAnswer: "1) Encapsulation - bundling data and methods. 2) Inheritance - acquiring properties of another class. 3) Polymorphism - many forms. 4) Abstraction - hiding implementation details.", estimatedTime: 15, marks: 2, tags: ["pillars", "OOP"] },
    { id: "CH19-VIV-002", difficulty: "easy", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "What is the difference between encapsulation and abstraction?", sampleAnswer: "Encapsulation hides data by making fields private with public methods. Abstraction hides implementation by showing only essential features. Encapsulation is about 'how' data is protected; abstraction is about 'what' is shown.", estimatedTime: 20, marks: 2, tags: ["encapsulation", "abstraction", "difference"] },
    { id: "CH19-VIV-003", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "What is the difference between IS-A and HAS-A relationships?", sampleAnswer: "IS-A is created by inheritance (a Dog IS-A Animal). HAS-A is created by using objects as fields (a Car HAS-A Engine). IS-A is about type hierarchy; HAS-A is about composition.", estimatedTime: 20, marks: 2, tags: ["IS-A", "HAS-A", "difference"] },
    { id: "CH19-VIV-004", difficulty: "medium", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "How do the four OOP pillars work together?", sampleAnswer: "Inheritance enables polymorphism (overriding). Encapsulation supports abstraction (hiding data). Abstraction defines contracts that inheritance implements. They complement each other to create robust, maintainable code.", estimatedTime: 20, marks: 2, tags: ["pillars", "together"] },
    { id: "CH19-VIV-005", difficulty: "hard", chapter: "OOP Concepts Overview", chapterId: 19, topic: "OOP Principles", question: "What are the benefits of OOP?", sampleAnswer: "1) Code reusability through inheritance. 2) Flexibility through polymorphism. 3) Security through encapsulation. 4) Simplicity through abstraction. 5) Maintainability through modular design. 6) Scalability for large projects.", estimatedTime: 25, marks: 3, tags: ["benefits", "OOP"] }
  ]
};

export default chapter19;
'''

# Write all chapters
for name, content in [("16-exception-handling", ch16), ("17-input-output", ch17), ("18-packages-access-modifiers", ch18), ("19-oop-concepts", ch19)]:
    with open(f"{qb}/{name}.js", "w") as f:
        f.write(content)
    print(f"Chapter {name} created")

# Create index.js
index = '''// Question Bank Index - Target95 ICSE Computer Applications
// Complete Java Question Bank with 19 chapters

import chapter1 from "./01-introduction";
import chapter2 from "./02-variables-data-types";
import chapter3 from "./03-operators";
import chapter4 from "./04-if-else";
import chapter5 from "./05-loops";
import chapter6 from "./06-methods";
import chapter7 from "./07-arrays";
import chapter8 from "./08-strings";
import chapter9 from "./09-constructors";
import chapter10 from "./10-encapsulation";
import chapter11 from "./11-inheritance";
import chapter12 from "./12-polymorphism";
import chapter13 from "./13-library-classes";
import chapter14 from "./14-recursion";
import chapter15 from "./15-searching-sorting";
import chapter16 from "./16-exception-handling";
import chapter17 from "./17-input-output";
import chapter18 from "./18-packages-access-modifiers";
import chapter19 from "./19-oop-concepts";

const questionBank = {
  chapters: [
    chapter1, chapter2, chapter3, chapter4, chapter5,
    chapter6, chapter7, chapter8, chapter9, chapter10,
    chapter11, chapter12, chapter13, chapter14, chapter15,
    chapter16, chapter17, chapter18, chapter19
  ],
  
  getChapterById: (id) => {
    return questionBank.chapters.find(ch => ch.id === id);
  },
  
  getChapterBySlug: (slug) => {
    return questionBank.chapters.find(ch => ch.slug === slug);
  },
  
  getAllChapters: () => {
    return questionBank.chapters;
  },
  
  getTotalQuestions: () => {
    let total = 0;
    for (const ch of questionBank.chapters) {
      total += (ch.mcqs || []).length;
      total += (ch.assertionReasons || []).length;
      total += (ch.trueFalse || []).length;
      total += (ch.fillBlanks || []).length;
      total += (ch.outputQuestions || []).length;
      total += (ch.errorFinding || []).length;
      total += (ch.programmingQuestions || []).length;
      total += (ch.debuggingQuestions || []).length;
      total += (ch.caseBasedQuestions || []).length;
      total += (ch.vivaQuestions || []).length;
    }
    return total;
  }
};

export default questionBank;
'''

with open(f"{qb}/index.js", "w") as f:
    f.write(index)
print("index.js created")
print("All chapters created successfully!")
