"use client";

import Link from "next/link";
import { useAuth } from "@/context/AuthContext";
import useStudentSettings from "@/app/hooks/useStudentSettings";
import Button from "../ui/Button";

export default function StudentSettings() {
  const { settings, ready, updateSetting } = useStudentSettings();
  const { logout } = useAuth();
  return <div className="mx-auto w-full max-w-4xl px-4 py-8 sm:px-6 lg:px-8"><header className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-700">Settings</p><h1 className="mt-2 text-3xl font-bold text-gray-900">Personalise your learning space</h1><p className="mt-2 text-sm text-gray-600">Your preferences are stored locally today and are ready to sync to your profile when Firestore is enabled.</p></header><div className="mt-6 space-y-6"><section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-gray-900">Profile</h2><p className="mt-1 text-sm text-gray-600">Manage your name, board, class, and avatar.</p><Link href="/profile" className="mt-4 inline-flex rounded-xl border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-800 hover:bg-gray-50">Open profile</Link></section><section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-gray-900">Preferences</h2><div className="mt-4 space-y-4"><label className="block text-sm font-semibold text-gray-700">Theme<select value={settings.theme} disabled={!ready} onChange={(event) => updateSetting("theme", event.target.value)} className="mt-2 w-full rounded-xl border border-gray-300 bg-white px-4 py-3 font-normal text-gray-900 sm:max-w-xs"><option value="system">System default</option><option value="light">Light</option><option value="dark">Dark</option></select></label><Toggle label="Learning notifications" description="Reminders and study milestones (placeholder)." checked={settings.notifications} onChange={(value) => updateSetting("notifications", value)} /><Toggle label="Private profile" description="Keep profile details private by default." checked={settings.profileVisible} onChange={(value) => updateSetting("profileVisible", value)} /></div></section><section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-gray-900">AI preferences</h2><label className="mt-4 block text-sm font-semibold text-gray-700">Tutor explanation style<select value={settings.aiDetail} disabled={!ready} onChange={(event) => updateSetting("aiDetail", event.target.value)} className="mt-2 w-full rounded-xl border border-gray-300 bg-white px-4 py-3 font-normal text-gray-900 sm:max-w-xs"><option value="guided">Guided steps</option><option value="concise">Concise</option><option value="detailed">Detailed</option></select></label></section><section className="rounded-3xl border border-red-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-gray-900">Account</h2><p className="mt-1 text-sm text-gray-600">Sign out securely on this device.</p><Button variant="outline" onClick={logout} className="mt-4 border-red-300 text-red-700 hover:bg-red-50">Log out</Button></section></div></div>;
}

function Toggle({ label, description, checked, onChange }) { return <label className="flex cursor-pointer items-start justify-between gap-4 rounded-2xl border border-gray-200 p-4"><span><span className="block text-sm font-semibold text-gray-900">{label}</span><span className="mt-1 block text-sm font-normal text-gray-600">{description}</span></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="mt-1 h-5 w-5 shrink-0 accent-blue-600" /></label>; }
