"use client";

import Link from "next/link";
import usePersonalizedRoadmap from "@/app/hooks/usePersonalizedRoadmap";
import { formatRelativeDate } from "@/lib/learningRoadmap";

const roadmapSteps = ["Subject", "Chapter", "Topic", "Practice", "Revision", "Mock Test", "Completed"];

export default function PersonalizedLearning() {
  const { chapters, recommendations, achievements, currentChapter, recentlyViewed, mockTests, stats } = usePersonalizedRoadmap();
  const overallProgress = chapters.length ? Math.round((stats.completed / chapters.length) * 100) : 0;
  return <div className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><header className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-700">My learning</p><div className="mt-3 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-bold text-gray-900 sm:text-4xl">Your personalised roadmap</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-gray-600">Follow a focused path from concepts and practice through revision and mock-test readiness.</p></div><div className="rounded-2xl bg-blue-50 px-5 py-3 text-sm font-semibold text-blue-800">{overallProgress}% syllabus progress</div></div><RoadmapSteps progress={overallProgress} /></header><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4" aria-label="Study statistics"><Stat label="Questions solved" value={stats.solved} /><Stat label="Accuracy" value={`${stats.accuracy}%`} /><Stat label="Current streak" value={`${stats.currentStreak} days`} /><Stat label="Learning time" value={`${stats.learningMinutes} min`} /></section><section className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><ContinueLearning chapter={currentChapter} mockTest={mockTests[0]} recentlyViewed={recentlyViewed} /><Recommendations recommendations={recommendations} /></section><section className="mt-6 rounded-3xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold text-gray-900">Chapter progress</h2><p className="mt-1 text-sm text-gray-600">Keep each chapter moving with a clear next action.</p></div><span className="text-sm font-semibold text-blue-700">{stats.completed}/{chapters.length} completed</span></div><div className="mt-5 space-y-4">{chapters.map((chapter) => <ChapterCard key={chapter.slug} chapter={chapter} />)}</div></section><section className="mt-6 grid gap-6 lg:grid-cols-2"><StudyStats stats={stats} /><Achievements achievements={achievements} /></section></div>;
}
function RoadmapSteps({ progress }) { return <ol className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{roadmapSteps.map((step, index) => <li key={step} className={`rounded-xl border px-3 py-2 text-center text-xs font-semibold ${progress >= Math.round(((index + 1) / roadmapSteps.length) * 100) ? "border-blue-200 bg-blue-50 text-blue-700" : "border-gray-200 bg-gray-50 text-gray-500"}`}>{step}</li>)}</ol>; }
function Stat({ label, value }) { return <article className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><p className="text-sm text-gray-600">{label}</p><p className="mt-2 text-2xl font-bold text-gray-900">{value}</p></article>; }
function ContinueLearning({ chapter, mockTest, recentlyViewed }) { return <article className="rounded-3xl border border-blue-200 bg-white p-6 shadow-sm"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-blue-700">Continue learning</p><h2 className="mt-2 text-2xl font-bold text-gray-900">{chapter?.title || "Start your Java journey"}</h2><p className="mt-2 text-sm text-gray-600">{chapter ? `${chapter.remaining} questions remain · ${chapter.estimatedCompletion} estimated` : "Choose a chapter to begin."}</p><div className="mt-5 flex flex-wrap gap-3"><Link href={chapter ? `/java/${chapter.slug}` : "/java"} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Resume chapter</Link><Link href="/mock-test" className="rounded-xl border border-gray-300 px-4 py-2.5 text-sm font-semibold text-gray-800 hover:bg-gray-50">{mockTest ? "Review mock tests" : "Take a mock test"}</Link></div>{recentlyViewed.length ? <p className="mt-5 text-xs text-gray-500">Recently viewed: {recentlyViewed.slice(0, 3).join(" · ")}</p> : null}</article>; }
function Recommendations({ recommendations }) { return <aside className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-gray-900">Recommended next</h2><div className="mt-4 space-y-3">{recommendations.map((item) => <div key={item.id} className="rounded-2xl bg-slate-50 p-4"><p className="text-sm font-semibold text-gray-900">{item.title}</p><p className="mt-1 text-xs leading-5 text-gray-600">{item.description}</p><Link href={item.href} className="mt-3 inline-flex text-xs font-semibold text-blue-700 hover:text-blue-800">{item.action} →</Link></div>)}</div></aside>; }
function ChapterCard({ chapter }) { return <article className="rounded-2xl border border-gray-200 p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><h3 className="text-lg font-bold text-gray-900">{chapter.title}</h3><p className="mt-1 text-sm text-gray-600">Last attempt: {formatRelativeDate(chapter.lastAttempt)}</p></div><Link href={`/java/${chapter.slug}`} className="inline-flex shrink-0 justify-center rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">{chapter.solved ? "Resume" : "Start"}</Link></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-gray-200"><div className="h-full rounded-full bg-blue-600" style={{ width: `${chapter.completion}%` }} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-6"><Metric label="Total" value={chapter.total} /><Metric label="Solved" value={chapter.solved} /><Metric label="Remaining" value={chapter.remaining} /><Metric label="Accuracy" value={`${chapter.accuracy}%`} /><Metric label="Estimate" value={chapter.estimatedCompletion} /><Metric label="Progress" value={`${chapter.completion}%`} /></dl></article>; }
function Metric({ label, value }) { return <div><dt className="text-xs text-gray-500">{label}</dt><dd className="mt-1 font-semibold text-gray-900">{value}</dd></div>; }
function StudyStats({ stats }) { return <section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-gray-900">Study stats</h2><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3"><Stat label="Daily progress" value={`${Math.min(stats.solved, 10)}/10`} /><Stat label="Weekly progress" value={`${stats.weeklyProgress}/35`} /><Stat label="Monthly progress" value={`${stats.monthlyProgress}/120`} /><Stat label="Accuracy trend" value={`${stats.accuracy}%`} /><Stat label="Current streak" value={`${stats.currentStreak} days`} /><Stat label="Best streak" value={`${stats.bestStreak} days`} /></div></section>; }
function Achievements({ achievements }) { return <section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-gray-900">Achievements</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{achievements.map((item) => <article key={item.id} className={`rounded-2xl border p-4 ${item.unlocked ? "border-green-200 bg-green-50" : "border-gray-200 bg-gray-50 opacity-70"}`}><p className="text-sm font-bold text-gray-900">{item.title}</p><p className="mt-1 text-xs leading-5 text-gray-600">{item.description}</p><p className={`mt-3 text-xs font-semibold ${item.unlocked ? "text-green-700" : "text-gray-500"}`}>{item.unlocked ? "Unlocked" : "Locked"}</p></article>)}</div></section>; }
