// Firestore Collection Definitions
export const COLLECTIONS = {
  USERS: "users",
  SUBJECTS: "subjects",
  CHAPTERS: "chapters",
  QUESTIONS: "questions",
  BOOKMARKS: "bookmarks",
  PROGRESS: "progress",
  MOCK_TESTS: "mockTests",
  RESULTS: "results",
  LEADERBOARD: "leaderboard",
};

// Collection Schema Definitions
export const SCHEMAS = {
  USER: {
    uid: "",
    name: "",
    email: "",
    role: "student", // student, teacher, admin
    photoURL: "",
    createdAt: null,
    updatedAt: null,
  },
  QUESTION: {
    subjectId: "",
    chapterId: "",
    difficulty: "medium", // easy, medium, hard
    question: "",
    options: [],
    answer: "",
    explanation: "",
    tags: [],
    createdAt: null,
    updatedAt: null,
  },
  PROGRESS: {
    userId: "",
    subjectId: "",
    chapterId: "",
    questionsSolved: 0,
    correctAnswers: 0,
    accuracy: 0,
    studyTime: 0,
    lastVisited: null,
    streak: 0,
  },
  SUBJECT: {
    name: "",
    icon: "",
    description: "",
    totalChapters: 0,
    totalQuestions: 0,
    color: "",
    createdAt: null,
    updatedAt: null,
  },
  CHAPTER: {
    subjectId: "",
    name: "",
    description: "",
    order: 0,
    totalQuestions: 0,
    isPublished: false,
    createdAt: null,
    updatedAt: null,
  },
  BOOKMARK: {
    userId: "",
    questionId: "",
    notes: "",
    createdAt: null,
  },
  MOCK_TEST: {
    name: "",
    description: "",
    subjectId: "",
    duration: 0,
    totalQuestions: 0,
    passingScore: 0,
    scheduledDate: null,
    isActive: false,
    createdAt: null,
    updatedAt: null,
  },
  RESULT: {
    userId: "",
    mockTestId: "",
    score: 0,
    correctAnswers: 0,
    totalQuestions: 0,
    timeTaken: 0,
    completedAt: null,
  },
  LEADERBOARD_ENTRY: {
    userId: "",
    name: "",
    photoURL: "",
    totalXP: 0,
    questionsSolved: 0,
    accuracy: 0,
    streak: 0,
    lastUpdated: null,
  },
};