"use client";

import Link from "next/link";
import useGamification from "@/app/hooks/useGamification";
import LevelProgress from "./LevelProgress";
import MotivationPanel from "./MotivationPanel";

export default function DailyChallenge() {
  const game = useGamification();
  return <div className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><header className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-blue-700">Daily challenge</p><h1 className="mt-2 text-3xl font-bold text-gray-900 sm:text-4xl">{game.challenge.title}</h1><p className="mt-2 text-sm text-gray-600">A focused Java set designed to build a consistent study habit.</p></header><div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><div className="grid grid-cols-2 gap-4 sm:grid-cols-4"><Metric label="Questions" value={game.challenge.questions} /><Metric label="Difficulty" value={game.challenge.difficulty} /><Metric label="Estimated time" value={game.challenge.estimatedTime} /><Metric label="Reward" value={`${game.challenge.reward} XP`} /></div><div className="mt-6 rounded-2xl bg-slate-50 p-5"><p className="text-sm font-semibold text-gray-900">Focus topic</p><p className="mt-1 text-sm text-gray-600">{game.challenge.topic}</p></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href="/question-bank" className="inline-flex justify-center rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white hover:bg-blue-700">Open challenge set</Link><button type="button" onClick={game.completeChallenge} disabled={game.challengeComplete} className="rounded-xl border border-gray-300 bg-white px-5 py-3 text-sm font-semibold text-gray-900 disabled:cursor-not-allowed disabled:opacity-60">{game.challengeComplete ? "Challenge complete" : "Mark complete and claim XP"}</button></div></section><aside className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-gray-600">Next challenge in</p><p className="mt-2 text-4xl font-bold text-gray-900">{game.countdown}</p><p className="mt-3 text-sm text-gray-600">Completion status: <span className="font-semibold text-green-700">{game.challengeComplete ? "Complete" : "In progress"}</span></p></aside></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><LevelProgress xp={game.xp} level={game.level} nextLevel={game.nextLevel} progress={game.levelProgress} /><MotivationPanel messages={game.motivation} /></div></div>;
}
function Metric({ label, value }) { return <div className="rounded-2xl border border-gray-200 p-4"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-sm font-bold text-gray-900">{value}</p></div>; }
