"use client";

import useGamification from "@/app/hooks/useGamification";
import { LEADERBOARD, XP_REWARDS } from "@/lib/gamification";
import LevelProgress from "./LevelProgress";
import MotivationPanel from "./MotivationPanel";

export default function RewardsCenter() {
  const game = useGamification();
  const unlocked = game.badges.filter((badge) => badge.unlocked);
  return <div className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><header className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-blue-700">Rewards</p><h1 className="mt-2 text-3xl font-bold text-gray-900 sm:text-4xl">Progress worth celebrating</h1><p className="mt-2 text-sm text-gray-600">Earn experience through learning, stay consistent, and unlock milestones along the way.</p></header><div className="mt-6"><LevelProgress xp={game.xp} level={game.level} nextLevel={game.nextLevel} progress={game.levelProgress} /></div><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Earned XP" value={game.xp} /><Stat label="Unlocked badges" value={`${unlocked.length}/${game.badges.length}`} /><Stat label="Current streak" value={`${game.stats.currentStreak} days`} /><Stat label="Questions solved" value={game.stats.solved} /></section><section className="mt-6 grid gap-6 lg:grid-cols-2"><Badges badges={game.badges} /><Rewards rewards={game.recentRewards} /></section><section className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Leaderboard /><MotivationPanel messages={game.motivation} /></section></div>;
}
function Stat({ label, value }) { return <article className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><p className="text-sm text-gray-600">{label}</p><p className="mt-2 text-2xl font-bold text-gray-900">{value}</p></article>; }
function Badges({ badges }) { return <section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-gray-900">Badges</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{badges.map((badge) => <article key={badge.id} className={`rounded-2xl border p-4 ${badge.unlocked ? "border-green-200 bg-green-50" : "border-gray-200 bg-gray-50 opacity-70"}`}><p className="text-sm font-bold text-gray-900">{badge.title}</p><p className="mt-1 text-xs leading-5 text-gray-600">{badge.description}</p><p className={`mt-3 text-xs font-semibold ${badge.unlocked ? "text-green-700" : "text-gray-500"}`}>{badge.unlocked ? "Unlocked" : "Locked"}</p></article>)}</div></section>; }
function Rewards({ rewards }) { return <section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-gray-900">Rewards activity</h2><div className="mt-5 space-y-3">{rewards.map((reward) => <div key={reward.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><span className="text-sm font-semibold text-gray-900">{reward.title}</span><span className="text-sm font-bold text-yellow-700">+{reward.xp} XP</span></div>)}<div className="rounded-2xl border border-dashed border-gray-300 p-4 text-sm text-gray-600">Upcoming: complete a chapter for +{XP_REWARDS.chapter} XP, or finish a mock test for +{XP_REWARDS.mockTest} XP.</div></div></section>; }
function Leaderboard() { return <section className="overflow-hidden rounded-3xl border border-gray-200 bg-white p-6 shadow-sm"><div><h2 className="text-xl font-bold text-gray-900">Leaderboard</h2><p className="mt-1 text-sm text-gray-600">Preview data; Firebase rankings will replace this list.</p></div><div className="mt-5 overflow-x-auto"><table className="min-w-[560px] w-full text-left text-sm"><thead className="border-b border-gray-200 text-xs uppercase tracking-wide text-gray-500"><tr><th className="pb-3">Rank</th><th className="pb-3">Student</th><th className="pb-3">XP</th><th className="pb-3">Solved</th><th className="pb-3">Accuracy</th></tr></thead><tbody>{LEADERBOARD.map((student) => <tr key={student.rank} className="border-b border-gray-100 last:border-0"><td className="py-3 font-bold text-gray-900">{student.rank}</td><td className="py-3 font-semibold text-gray-900">{student.student}</td><td className="py-3 text-yellow-700">{student.xp}</td><td className="py-3 text-gray-700">{student.solved}</td><td className="py-3 text-gray-700">{student.accuracy}%</td></tr>)}</tbody></table></div></section>; }
